---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i went to install git
    apt:
      name: git
      state: present
  - name: i want install tree
    apt:
      name: tree
      state: present

  - name: i want install webserver
    apt:
      name: apache2
      state: present 
      
  - name: i went start my webserver
    service:
       name: apache2
       state: started