apiVersion: apps/v1
kind: Deployment
metadata:
 name: myjavaappimage31dec21-deploy
 labels:
   app: myjavaappimage31dec21
spec:
  replicas: 3
  selector:
    matchLabels:
        app: myjavaappimage31dec21
  template:
    metadata:
       labels:
        app: myjavaappimage31dec21
    spec:
      containers:
      - name: myjavaappimage31dec21-container
        image: madhu1997/myjavaappimage31dec21:1
        ports:
        - containerPort: 8080