apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaappimage31dec21-rc
spec:
   replicas: 3
   selector: 
     app: myjavaappimage31dec21
   template:
     metadata:
       labels:
          app: myjavaappimage31dec21
     spec:
        containers:
        - name: myjavaappimage31dec21-containe  
          image: madhu1997/myjavaappimage31dec21:1
          ports:
          - containerPort: 8080 