apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector: 
     app: myjekins-pod
   template:
     metadata:
       labels:
          app: myjekins-pod
     spec:
        containers:
        - name: myjenkins-container   
          image: jenkins:2.60.3
          ports:
          - containerPort: 8080  