apiVersion: v1
kind: Service
metadata:
  name: myjavaappimage31dec21-svc
  labels:
     app: myjavaappimage31dec21
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app: myjavaappimage31dec21